name = "test_renovate_gleam"
version = "1.0.0"

# NOTE: All deps are outdated

[dependencies]
wisp = ">= 0.14.0 and < 0.15.0"
gleam_stdlib = "<= 0.38.0"
ids = "== 0.12.0"

[dev-dependencies]
gleeunit = ">= 1.1.0"
