name = "test_renovate_gleam"
version = "1.0.0"

[dependencies]
wisp = ">= 0.14.0 and < 1.2.1"
gleam_stdlib = ">= 0.38.0 and < 1.0.0"
jackson = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
