name = "test_renovate_gleam"
version = "1.0.0"

[dependencies]
wisp = "< 1.1.1"
gleam_stdlib = ">= 0.38.0 and < 1.0.0"
ids = ">= 0.10.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
